### ISSUE TITLE
Answer on non-recursive flatmap incorrect

### ISSUE THREAD

**Issue by joshrliben** [cqframework/cqf-exercises#1]
https://github.com/cqframework/cqf-exercises/blob/59dd08fee775da6c329c107e5cd590410bec7f2f/input/cql/Exercises04Key.cql#L238

Currently looks like:
`= { 1, 2, 3, { 'a', 'b' }, 'x', 'y' }`

Think it should be:
`= { 1, 2, 3, { 'a', 'b' }, {'x', 'y'} }`

@brynrhodes

**Comment by brynrhodes** [comment]
Fixed, thank you!
